version: '3.8'

services:
  mariadb:
    build: .
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: dbms
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - sql-files:/docker-entrypoint-initdb.d
    networks:
      - mariadb_network

volumes:
  sql-files:
    driver: local

networks:
  mariadb_network:
    driver: bridge
