version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: manas
      POSTGRES_PASSWORD: manasispro
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: mcb76593@gmail.com
      PGADMIN_DEFAULT_PASSWORD: manasispro
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  pgdata:
